name: Auto Frozen Moq - Release

on:
  workflow_run:
    workflows: ["Auto Frozen Moq - CI"]
    branches: [ main ]
    types:
      - completed
jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.*
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish to NuGet
        run: echo "version=`cat ./version` \
\
major=0 \
minor=0 \
build=0 \
\ 
regex='([0-9]+).([0-9]+).([0-9]+)' \
if [[ $version =~ $regex ]]; then \
  major='${BASH_REMATCH[1]}' \
  minor='${BASH_REMATCH[2]}' \
  build='${BASH_REMATCH[3]}' \
fi \
\
build=$((build + 1))\
\
echo $build >> ./version \
"
